services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  backend:
    build:
      context: ../server
      dockerfile: backend.Dockerfile
    image: backend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
